### ISSUE TITLE
VID/PID Database

### ISSUE THREAD

**Issue by ungureanuvladvictor** [praveendath92/bard-linux#6]
A few months ago http://usbhost.chainfire.eu/ had a list with vid/pid that support USB Host capabilities. We should find a way to query that data and include it in a .h file so the user does not need to edit the module code. 

Now the server is down, maybe contact chainfire on IRC...

**Comment by praveendath92** [comment]
An exhaustive list would be perfect! I was actually thinking, if we should write a small program that can do the whole setup for unlisted devices.

**Comment by ungureanuvladvictor** [comment]
Check #android-dev maybe Cahinfire is there...he should have some db with them i think.

**Comment by ungureanuvladvictor** [comment]
http://www.linux-usb.org/usb.ids

**Comment by praveendath92** [comment]
Thanks @ungureanuvladvictor 
That's one heck of list! How do we extract Android devices from this? Also, we need interface, class and subclass information!

**Comment by ungureanuvladvictor** [comment]
can't we match just with vid/pid ?

**Comment by praveendath92** [comment]
Then we will have the duplicate probing problem. I would prefer matching just vip/pid and ignoring the probe for unwanted interface. But then, this means we should have a way to identify the right interface.

**Comment by praveendath92** [comment]
I have some good news on this one. I just ran a quick test and found that we can do the ADK setup up any of the available interfaces - I suppose this comes from the fact that we are sending USB Control messages. 

So, as long as at least one interface is probed, we are good. 

This means, we can ignore the probe function call from system for the second interface and run the setup only once. Also, we don't need make register a device file at all for adk setup.

**Comment by praveendath92** [comment]
We can apply a device id filter like,

```
{ .idVendor = VID4,
  .match_flags = USB_DEVICE_ID_MATCH_VENDOR,
},
```
and work with only vendor ids. That explains why [Google provided only vendor ids list][1].

To save some effort, I also found [this][2]

[1]: http://developer.android.com/tools/device.html#VendorIds
[2]: https://android.googlesource.com/platform/system/core/+/android-4.4_r1/adb/usb_vendors.c

**Comment by praveendath92** [comment]
The list spans over 8000+ devices and directly supports new devices coming from the known brands!
